[package]
name = "starknet"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "starknet"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34.0"
starknet = "0.12.0"
starknet-types-core = "0.1.7"
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
